repos:
  - repo: https://github.com/myint/autoflake
    rev: v1.6.1
    hooks:
      - id: autoflake
        args: [--in-place, --remove-all-unused-imports, --ignore-init-module-imports]
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        args: ["--profile", "black"]
  - repo: https://github.com/psf/black
    rev: 22.8.0
    hooks:
      - id: black
        language_version: python3.8
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        additional_dependencies: ["flake8-builtins==1.5.3", "flake8-bugbear==20.1.1"]
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.28.0
    hooks:
      - id: yamllint
  - repo: https://github.com/tier4/pre-commit-hooks-ros
    rev: v0.7.0
    hooks:
      - id: prettier-xacro
      - id: prettier-package-xml
      - id: sort-package-xml
